"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP_NAME = 'Convertor sizes of images'
APP = ['main.py']
DATA_FILES = []
OPTIONS = {
    'iconfile': 'app_icon.ico',
}

setup(
    app=APP,
    name=APP_NAME,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
